### ISSUE TITLE
Issue with "Entity" when creating menu item

### ISSUE THREAD

**Issue by mattmillen888** [VirtusLab-Open-Source/strapi-plugin-navigation#153]
I am having an issue with "Entity" when creating a Navigation menu. It just shows up as white in the menu so i don't really know what it is or does?.

I have created a video to show whats happening. We can select a white menu item and it works and creates menu item but as I create more menu items the selection list gets smaller and then i cant create any more menu items so it's obviously linked to the page posts somehow?

I have a question? What is Entity and is this a configuration error? I have used the below plugin config recommended

module.exports = ({ env }) => ({
  navigation: {
    enabled: true,
    config: {
      additionalFields: ["audience"],
      contentTypes: ["api::page.page"],
      contentTypesNameFields: {
        "api::page.page": ["title"],
      },
      allowedLevels: 2,
      gql: {},
    },
  },
});

https://user-images.githubusercontent.com/25214970/154438806-70cc802e-e43b-4b48-a261-96350acad21d.mov

any help greatly appreciated. If i'm clear whats happening to fix it or maybe its a bug

Thanks

**Comment by ltsNotMike** [comment]
Hello @mattmillen888, thank you for pointing out this bug. I've tried to reproduce it but with no luck. 
Can you please provide me with this informations:

- What version of strapi and strapi-plugin-navigation are you using?
- What version of node are you using?
- Does the browser console print any errors? If yes please provide screenshots of these errors.

**Comment by mattmillen888** [comment]
"@strapi/strapi": "^4.0.8",
"strapi-plugin-navigation": "^2.0.2"
node v14.18.3

No console errors showing in browser

**Comment by ltsNotMike** [comment]
I found out that this kind of behavior happens when the content type doesn't have a name field. This can happen by either mismatch between your config and content type structure or by editing content type structure. 

1. Make sure that your `Page` content type has the `title` field that you provided inside config as a name field. 
2. Make sure that entities of `Page` content type don't have the `title` field empty. Changing content types structure can empty some of the fields and cause this bug.

Please let me know if this helped with your problem. In the meantime, I will try to add notification if there is a mismatch and implement safety measures if this bug occurs.

https://user-images.githubusercontent.com/20796806/154482092-0b8fa753-b89e-4bbc-afb8-919ecb67bb05.mov

**Comment by mattmillen888** [comment]
Excellent thanks for this information. it works really well now!

**Comment by cyp3rius** [comment]
Released as part of `v2.0.3`
