### ISSUE TITLE
Need to add multiple menus with different content types

### ISSUE THREAD

**Issue by mattmillen888** [VirtusLab-Open-Source/strapi-plugin-navigation#157]
For some reason when i add a second menu item with different content type other than api::page.page it wont show up when i create a new menu in admin. It only ever shows "Pages", where as it should also now show "HelpForms"

for example i have created a new content type called "api::help-form.help-form" and it wont show in the dropdown? any ideas why?

My config is below::

module.exports = ({ env }) => ({
  navigation: {
    enabled: true,
    config: {
      additionalFields: ["audience"],
      contentTypes: ["api::page.page", "api::help-form.help-form"],
      contentTypesNameFields: {
        "api::page.page": ["title"],
        "api::help-form.help-form": ["title"],
      },
      allowedLevels: 2,
      gql: {},
    },
  },
});
<img width="849" alt="Screen Shot 2022-02-19 at 09 14 56" src="https://user-images.githubusercontent.com/25214970/154768612-0439ad52-ed25-4dba-9d02-ee4b917b67f4.png">

**Comment by mattmillen888** [comment]
Its ok I solved this. maybe worth putting in documentation that you need to rebuild admin "yarn build" for the Navigation Plugin to show-up in settings  otherwise this don't work as they should :)

**Comment by ltsNotMike** [comment]
Since v2.0.2 config file is only a store for restoring configuration. If you changed it you have to restore config through the Settings Page for the file to be synchronized with the working configuration. 

Creating your own configuration through the `plugins.js` file is very error-prone. Please try to avoid it and use the plugin's new Settings Page to avoid all possible problems with configuration.

**Comment by cyp3rius** [comment]
Closing as answered.
