### ISSUE TITLE
Extend Lifecycle hook

### ISSUE THREAD

**Issue by Meljesson** [VirtusLab-Open-Source/strapi-plugin-navigation#251]
I tried modifying the lifecycle hook on server/content-type/navigation-item/lifecycle.js
A simple console.log would not fire

**Comment by ltsNotMike** [comment]
Hi @Meljesson,

I will need some more information to investigate this issue. Can you please provide me with:
- What version of strapi and our plugin are you using? 
- Which option of extending content types have you used? 
   - the content-types of the original plugin,
   - the content-types overriden by the declarations in the schema defined in ./src/extensions/plugin-name/content-types/content-type-name/schema.json
   - the content-types declarations in the content-types key exported from strapi-server.js
   - the content-types declarations in the register() function of the Strapi application
 - If possible please provide some kind of screenshot or snippet

**Comment by Meljesson** [comment]
Hi @ltsNotMike ,

I am using Strapi v4 and using the latest version of the plugin. I've solved the issue on my end. 
The issue was that the format for lifecycle was still in the format of v3 of the plugin instead of v4 format.

<img width="550" alt="Screen Shot 2022-07-24 at 8 49 30 PM" src="https://user-images.githubusercontent.com/29881184/180673644-7c995c58-307f-4f33-9b12-10ac7b5a8f4e.png">

In the plugin located in server/content-types/model/lifecycle.js , the lifecycle file is supposed to be name lifecycles.js 
and in the format of 

<img width="466" alt="Screen Shot 2022-07-24 at 8 48 07 PM" src="https://user-images.githubusercontent.com/29881184/180673585-f32c688d-08d1-4ce4-8b96-80cc44c1b1cf.png">

What I did was add lifecycles.js file in the models I wanted a lifecycle hook. I used patch-package to apply my extensions for Strapi V4

**Comment by ltsNotMike** [comment]
Yeah, I just realized that our hooks are not even used since they have the wrong names and structure. I'll remove them in a refactor commit since they're unnecessary. Thank you for pointing that issue out. 

In the future, if you want to customize the behavior of our plugin please do it through the extensions folder.  Or if we lack some functionality that you need, please feel free to open an issue with a feature request.

**Comment by Meljesson** [comment]
For some reason, customizing the plugin through the extensions folder in Strapi V4 doesn't seem to do anything. My path is
./src/extensions/strapi-plugin-navigation/content-types/navigation-item/ and it doesn't work for both schema.json and lifecycles.js

**Comment by ltsNotMike** [comment]
Try doing it with `./src/extensions/navigation/content-types/navigation-item` and it should work. This is because we register our plugin inside strapi as `navigation`. You can see what plugins names are by running strapi with yarn strapi console and looking through the strapi object. 
<img width="566" alt="strapi_console" src="https://user-images.githubusercontent.com/20796806/180812923-a1b57770-224f-45f8-b678-97e9d0142f4f.png">

**Comment by Meljesson** [comment]
That seems to have worked. Though only for schema.json and not the new lifecycle structure for v4. But thanks for your help!

**Comment by cyp3rius** [comment]
Released as part of `v2.2.0`
