### ISSUE TITLE
Mailto: Regex makes no sense

### ISSUE THREAD

**Issue by Maxdola** [VirtusLab-Open-Source/strapi-plugin-navigation#254]
The new Regex you've added for mailto makes no sense since you are only supporting TDLs with 2-4 characters. 
.online for example has more....

**Comment by Maxdola** [comment]
tel:+49121212 International Numbers also dont work

**Comment by cyp3rius** [comment]
@CodeVoyager Can you please take a look on provided examples and lift those rules?

**Comment by Maxdola** [comment]
Thanks @cyp3rius.

Also Some Domains including .DE allow äöü in the domain which is also not supported. Only if you use Punycode.

**Comment by CodeVoyager** [comment]
Sure, will take care of this.

**Comment by CodeVoyager** [comment]
Hi @Maxdola 

I prepared new PR that will address some of your requests. PR is linked.

One feature that we will not implement at this point is extending logins and domain names to allow non-ascii characters. Adding all of the would be time consuming and may introduce new bugs or allowing everything that is not a space character would lax regex too much. Since we try to cater to wide audience and need to balance usability and security this decision was made. I recommend using Punycode for now. Sorry for an inconvenience!

**Comment by Maxdola** [comment]
Hi,
Thank you for adjusting the Regex.

But I have to admit I don't agree a 100% with your second statement. I understand the reasoning behind your statement. But you are making life harder for people with special domains, which are still not 100% supported and the Punycode version just does not look good when you hover over it.

But nevertheless, I think you will find a solution for it in the future.

One thing that came to my mind is an Expert mode enabled in the Settings which disables all Regex validation. This should make everybody happy.

**Comment by cyp3rius** [comment]
We will think about such possibility @Maxdola, but as for now and taking most of use cases extended regex validation should work. Already merged and should be released by end of this week.

**Comment by cyp3rius** [comment]
Released as part of `2.2.1`
