### ISSUE TITLE
Navigation configuration page under the Strapi settings page doesn't show with latest version of Strapi

### ISSUE THREAD

**Issue by GitHyppa** [VirtusLab-Open-Source/strapi-plugin-navigation#310]
I noticed that there was no configuration page when I installed this plugin for the first time with the latest version of Strapi. After downgrading from 4.6.2 to 4.6.0 it worked perfectly fine. Not sure if it's only me or everyone else but I thought it would be a good idea to let you know about it.

Steps to reproduce, create a new Strapi project with the latest version of Strapi, then follow the Navigation plugin guide https://market.strapi.io/plugins/strapi-plugin-navigation#install-now-section and you should notice that there is no Navigation configuration page in the Strapi settings page.

**Comment by NeekoDev** [comment]
Hi, got the same problem.

**Comment by cyp3rius** [comment]
May I ask for the stack trace? Trying to reproduce this issue on 4.6.x and 4.7.x

**Comment by cyp3rius** [comment]
Cannot reproduce. In case of issue occurrence please re-open this issue and provide proper error stack trace, strapi console logs and your config.

**Comment by certainlyakey** [comment]
Same here, but it seems i've found a solution. 

A bit of explainer – we use Strapi as one package in an [nx](https://nx.dev/) based monorepo. The Strapi package is located in `/monorepo/packages/cms`. However nx works like this that most of the node_modules for packages get installed in the root (`/monorepo/node_modules`) and not to the package folder (`/monorepo/packages/cms/node_modules`).

So far we used Strapi 4.15.4 with strapi-plugin-navigation 2.3.1. After a while we decided to upgrade both to the latest versions (4.20.2 and 2.4.0).

After upgrading both and running `npm build && npm develop`, the plugin's settings were gone from the admin. No stack trace was given, everything looked normal both in command line and browser console. It could be seen that after upgrading the plugin entry in `.strapi/client/app.js` was removed. To recheck, I explicitly added `'navigation': {enabled: true}` to `config/plugins.js`, and got this error message: 

```
Error: Error loading the plugin navigation because navigation is not installed. Please either install the plugin or remove it's configuration. at Object.loadPlugins (/monorepo/node_modules/@strapi/strapi/dist/core/loaders/plugins/index.js:83:13) at async Strapi.loadPlugins (/monorepo/node_modules/@strapi/strapi/dist/Strapi.js:311:5) at async Promise.all (index 3) at async Strapi.register (/monorepo/node_modules/@strapi/strapi/dist/Strapi.js:341:5) at async Strapi.load (/monorepo/node_modules/@strapi/strapi/dist/Strapi.js:425:5)  at async Object.develop (/monorepo/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:837:28) at async develop (/monorepo/node_modules/@strapi/admin/dist/_chunks/develop-YNTGWKMC.js:61:5) at async Command.parseAsync (/monorepo/node_modules/commander/lib/command.js:923:5)at async Module.runStrapiCommand (/monorepo/node_modules/@strapi/strapi/dist/commands/index.js:130:3)
```

I've checked, and with Strapi 4.20.2, the latest version of the plugin gets installed to `/monorepo/packages/cms/node_modules`, however with 4.15.4 it gets installed into `/monorepo/node_modules`. Strapi looks for the plugin in the root of a monorepo, not in the package folder, and therefore with Strapi 4.20.2 it is not found. 

My workaround was to look at what Strapi version the plugin is dependent on [in the latest release](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/compare/v2.3.2...v2.4.0) (4.20.0), and downgrade from 4.20.2 to that one. 

So in general the issue is that for some reason strapi-plugin-navigation inside of an nx monorepo fails to install into the correct node_modules folder, unless the Strapi version in a project is 100% matched to what the plugin has been built against.

**Comment by BartekCK** [comment]
Hi, I encountered the same issue while working with turborepo. The problem occurred with Strapi version 4.23.0. After upgrading to 4.23.1, everything started working.

Versions of packages:

```json
"@strapi/admin": "4.23.1",
"@strapi/helper-plugin": "4.23.1",
"@strapi/data-transfer": "4.23.1"
```

are hardcoded. Perhaps there is an issue with the monorepo setup when the versions do not match the installed version of Strapi on the local machine.
