### ISSUE TITLE
Question - Why No Duplicate Menu Items

### ISSUE THREAD

**Issue by marcodeluca** [VirtusLab-Open-Source/strapi-plugin-navigation#391]
I need to add menu items for the same internal content entry and the component does not allow this. I'm assuming this is intentional? I do not see any setting to enable duplicate menu items.

Is there a reason why you are enforcing this? There are multiple business use cases that this is necessary. A work around would be allowing custom links without enforcing the http, for example allowing /my-path/my-page but this is not possible either. 

Am i missing an option to allow this?

**Comment by Adaphath** [comment]
+1 I don't understand the necessity either.
Is it needed for internal functionality?

**Comment by CodeVoyager** [comment]
Hi @marcodeluca and @Adaphath 

Current one entity limit per navigation is a left-over from previous Strapi version. There was relation persistence issue when the same entity was used in multiple navigation items.

There's a plan to remove this limitation in near future. At the moment I cannot say for sure when this will happen.

**Comment by xmak** [comment]
We have several clients that have a complex navigation tree and need to have different navigation items linking to the same page, for organizational and marketing reasons.

This is a much-needed feature, which for now we have circumvented by creating a new content type "Nav Item" that has a Realation field to choose a page, then in the navigation we link to this content type instead of to the page directly. It works, but it's cumbersome and bad practice to have a content type just to circumvent the lack of this feature.

Please allow linking to the same page from different navigation items it's truly needed in real-life situations.

**Comment by olivierneo** [comment]
Same problem here, a non user friendly solution : use the external url.

**Comment by fernandezremi** [comment]
Do you have any news about this feature request? We need to link different menu items to the same page without bypassing the problem!

**Comment by cyp3rius** [comment]
As for now the only solution is as @olivierneo provided. Because of heavy refactoring for v5, we're no longer working on feature requests to v4 as per release notes for [2.5.0](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/releases/tag/v2.5.0)

**Comment by Badlapje** [comment]
Personally i use the wrapper item and then enter the url manually

**Comment by vntw** [comment]
@cyp3rius sorry for the ping in an old issue, but this has been marked as completed but the restriction is still in 3.0.5 as far as I can see from the code (had the error pop up while testing the plugin). Should this work or is this not planned after all?
