### ISSUE TITLE
Unable to create another Menu in different locale

### ISSUE THREAD

**Issue by thewickest** [VirtusLab-Open-Source/strapi-plugin-navigation#414]
I have two situations here.

My Strapi setup has 3 locales (en, fr and ar) the first time that I enter the UI Navigation menu, the third locale does not show up, only en and fr. When I click the button to create another Menu (Manage) it let me creates the Menu but it doesn't show up after this. (the first problem that I have is solved now. The selector does show 3 locales now)
![imagen](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/99754651/91cd6646-e2f5-47ae-9228-9c303c764086)

When I look into the DB, I see that the Menu has been created without locale, that's why It doesn't show after the creation in the admin panel. If I modify the DB manually and add the missing locales, it does show up.
![imagen](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/99754651/d9bb40e2-bca7-4344-b6be-cb9a9f69f5d5)

    Strapi-plugin-navigation: 2.4.0
    Strapi: v4.20.1
    Node: 18.18.2
    NPM: 9.8.1

**Comment by CodeVoyager** [comment]
Hi @thewickest 

We're sorry for your inconvenience.

As a check steps I've to checks.

First on was to delete all navigations. (Simulating first run after plugin enabling). I was unable to detect any issues. `Main navigation` was created in all available locale version (4 in my case).

Second one was to just add a new navigation. With that I was able to reproduce the issue. I found out the reason and created PR to address it.

So for the first part of your query I'm not able to reproduce this issue one to one. Would re-iterate steps to reproduce it, please?

**Comment by RemiKalbe** [comment]
I'm having the same issue, 3 locales, one of them doesn't show up (and sometime the one that shows up changes). This plugin is very unstable as I've add other similar issues in multiple project.

**Comment by aftarfadilah** [comment]
I also have this issue.
I'm using 2 locales.
When I create a new Navigation, it doesn't show up because the `locale_code` is null. I have to edit it manually within the database. Then there's also a problem, the locale for that navigation is not created for all locale. It'll only be created if I create another navigation, but then after all menu for all locales generated, the `navigations_localizations_links` is not correctly linked causing my navigation to have 4 locale if I have 2 navigation that's not generated for all locale (ie. "de, de, en, en").
