### ISSUE TITLE
Navigations not showing in collections in v1.0.2

### ISSUE THREAD

**Issue by ScottEAdams** [VirtusLab-Open-Source/strapi-plugin-navigation#74]
Just installed 1.0.2 and after doing a yarn build I am no longer seeing any of the navigation models under collections types, not even the "navigations" model for adding/removing navigations.

**Comment by cyp3rius** [comment]
Hello @ScottEAdams,

thats expected as in the latest release we’ve introduced support for collections visibility in the left sidebar that Strapi introduced. Direct url to the change is available in the release notes of 1.0.2

That step has been done to avoid confusions because of lack of support for poly relations by built-in Content Manager.

If you’ve been using the collections directly, we can advice to copy their json files to the extensions/navigation/models directory and drop the pluginOptions section. Anyway Thats not a recommended way.

In the version 1.1 we are planning to introduce the native support for multiple navigation containers.

**Comment by ScottEAdams** [comment]
OK, thanks for the clarification. Sorry for the follow up question but does that mean that support for multiple navigation containers is currently not supported or is there some documentation for the plugin options that I am failing to understand? Previously I had just created more navigations than the "Main navigation" using the navigations collection type.

**Comment by cyp3rius** [comment]
In that case to enable it again, drop the lines introduced here: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/pull/70/files#diff-5473bb7557380462848d1cb53f7d6ede00dafb96a474db7db0582701e04db250

Simply copy the file to `extensions/navigation/models` and remove the lines. It will work as previously. Once we introduce the navite support for multi navigation, you'll be asked to remove the extension. We will ask for this in release notes.
