### ISSUE TITLE
Server Side Use of Audience field

### ISSUE THREAD

**Issue by mfreeman-xtivia** [VirtusLab-Open-Source/strapi-plugin-navigation#94]
Can the audience field be used server-side to constrain which navigation entries are returned on a particular REST call (perhaps by also using the user making the request)?

Or is this strictly an additional piece of metadata returned to the client to use as it sees fit?

**Comment by cyp3rius** [comment]
Hello @mfreeman-xtivia ,

By design that was a meta data, but it might be used as a filter of a query string: https://strapi.io/documentation/developer-docs/latest/developer-resources/content-api/content-api.html#api-parameters

Our logic consumes it so if you will user the prop like `audience.key` it should filter out and return only items based on the audience provided.
